from django.core.management.base import BaseCommand
from zodiac.models import ZodiacSign


class Command(BaseCommand):
    help = '12 burcu veritabanına yükler'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Burçlar yükleniyor...'))
        
        zodiac_data = [
            {
                'name': 'Koç',
                'name_en': 'Aries',
                'slug': 'koc',
                'symbol': '♈',
                'element': 'fire',
                'quality': 'cardinal',
                'ruling_planet': 'Mars',
                'date_range': '21 Mart - 19 Nisan',
                'start_month': 3,
                'start_day': 21,
                'end_month': 4,
                'end_day': 19,
                'description': 'Koç burcu enerjik, cesur ve lider ruhlu bireylerdir. Yeni başlangıçları seven ve maceraperest yapıları vardır.',
                'traits': 'Girişken, cesur, hırslı, kararlı, özgüvenli, bağımsız, rekabetçi',
                'strengths': 'Cesaret, liderlik, enerji, heyecan, motivasyon',
                'weaknesses': 'Sabırsızlık, agresiflik, düşünmeden hareket etme, bencillik',
                'compatibility': 'Aslan, Yay, İkizler, Kova',
                'lucky_numbers': '1, 9',
                'lucky_colors': 'Kırmızı, Turuncu',
                'lucky_day': 'Salı',
                'order': 1,
            },
            {
                'name': 'Boğa',
                'name_en': 'Taurus',
                'slug': 'boga',
                'symbol': '♉',
                'element': 'earth',
                'quality': 'fixed',
                'ruling_planet': 'Venüs',
                'date_range': '20 Nisan - 20 Mayıs',
                'start_month': 4,
                'start_day': 20,
                'end_month': 5,
                'end_day': 20,
                'description': 'Boğa burcu kararlı, güvenilir ve pratik bireylerdir. Güzelliği, konforu ve istikrarı seven bir yapıları vardır.',
                'traits': 'Kararlı, sadık, pratik, güvenilir, sabırlı, tutarlı',
                'strengths': 'İstikrar, güvenilirlik, kararlılık, dayanıklılık, sabır',
                'weaknesses': 'İnatçılık, değişime direnç, kıskançlık, aşırı sahiplenici',
                'compatibility': 'Başak, Oğlak, Yengeç, Balık',
                'lucky_numbers': '2, 6',
                'lucky_colors': 'Yeşil, Pembe',
                'lucky_day': 'Cuma',
                'order': 2,
            },
            {
                'name': 'İkizler',
                'name_en': 'Gemini',
                'slug': 'ikizler',
                'symbol': '♊',
                'element': 'air',
                'quality': 'mutable',
                'ruling_planet': 'Merkür',
                'date_range': '21 Mayıs - 20 Haziran',
                'start_month': 5,
                'start_day': 21,
                'end_month': 6,
                'end_day': 20,
                'description': 'İkizler burcu meraklı, iletişim yeteneği güçlü ve zeki bireylerdir. Çok yönlü ve uyumlu yapıları vardır.',
                'traits': 'Meraklı, iletişimci, zeki, uyumlu, esprili, hareketli',
                'strengths': 'İletişim, esneklik, zeka, öğrenme yeteneği, sosyallik',
                'weaknesses': 'Kararsızlık, yüzeysellik, huzursuzluk, tutarsızlık',
                'compatibility': 'Terazi, Kova, Koç, Aslan',
                'lucky_numbers': '3, 5',
                'lucky_colors': 'Sarı, Açık Mavi',
                'lucky_day': 'Çarşamba',
                'order': 3,
            },
            {
                'name': 'Yengeç',
                'name_en': 'Cancer',
                'slug': 'yengec',
                'symbol': '♋',
                'element': 'water',
                'quality': 'cardinal',
                'ruling_planet': 'Ay',
                'date_range': '21 Haziran - 22 Temmuz',
                'start_month': 6,
                'start_day': 21,
                'end_month': 7,
                'end_day': 22,
                'description': 'Yengeç burcu duygusal, koruyucu ve sezgisel bireylerdir. Aile ve ev yaşamına büyük önem verirler.',
                'traits': 'Duygusal, koruyucu, sezgisel, sadık, şefkatli, aileci',
                'strengths': 'Empati, şefkat, sadakat, sezgi, duygusal derinlik',
                'weaknesses': 'Aşırı duygusallık, içine kapanıklık, geçmişe takılma, savunmacılık',
                'compatibility': 'Akrep, Balık, Boğa, Başak',
                'lucky_numbers': '2, 7',
                'lucky_colors': 'Beyaz, Gümüş',
                'lucky_day': 'Pazartesi',
                'order': 4,
            },
            {
                'name': 'Aslan',
                'name_en': 'Leo',
                'slug': 'aslan',
                'symbol': '♌',
                'element': 'fire',
                'quality': 'fixed',
                'ruling_planet': 'Güneş',
                'date_range': '23 Temmuz - 22 Ağustos',
                'start_month': 7,
                'start_day': 23,
                'end_month': 8,
                'end_day': 22,
                'description': 'Aslan burcu özgüvenli, yaratıcı ve cömert bireylerdir. Doğal liderlik yetenekleri ve karizmaları vardır.',
                'traits': 'Özgüvenli, cömert, yaratıcı, karizmatik, tutkulu, dramatik',
                'strengths': 'Liderlik, yaratıcılık, cömertlik, cesaret, coşku',
                'weaknesses': 'Kibir, inatçılık, dikkat çekme ihtiyacı, bencillik',
                'compatibility': 'Koç, Yay, İkizler, Terazi',
                'lucky_numbers': '1, 4',
                'lucky_colors': 'Altın, Turuncu',
                'lucky_day': 'Pazar',
                'order': 5,
            },
            {
                'name': 'Başak',
                'name_en': 'Virgo',
                'slug': 'basak',
                'symbol': '♍',
                'element': 'earth',
                'quality': 'mutable',
                'ruling_planet': 'Merkür',
                'date_range': '23 Ağustos - 22 Eylül',
                'start_month': 8,
                'start_day': 23,
                'end_month': 9,
                'end_day': 22,
                'description': 'Başak burcu detaycı, analitik ve mükemmeliyetçi bireylerdir. Pratik ve yardımsever yapıları vardır.',
                'traits': 'Detaycı, analitik, mükemmeliyetçi, pratik, yardımsever, alçakgönüllü',
                'strengths': 'Analiz yeteneği, organizasyon, pratiklik, güvenilirlik, dikkat',
                'weaknesses': 'Aşırı eleştirellik, endişelilik, mükemmeliyetçilik, aşırı titizlik',
                'compatibility': 'Boğa, Oğlak, Yengeç, Akrep',
                'lucky_numbers': '5, 6',
                'lucky_colors': 'Gri, Bej',
                'lucky_day': 'Çarşamba',
                'order': 6,
            },
            {
                'name': 'Terazi',
                'name_en': 'Libra',
                'slug': 'terazi',
                'symbol': '♎',
                'element': 'air',
                'quality': 'cardinal',
                'ruling_planet': 'Venüs',
                'date_range': '23 Eylül - 22 Ekim',
                'start_month': 9,
                'start_day': 23,
                'end_month': 10,
                'end_day': 22,
                'description': 'Terazi burcu dengeli, adil ve diplomatik bireylerdir. Uyum, güzellik ve ilişkilere önem verirler.',
                'traits': 'Dengeli, adil, diplomatik, sosyal, zarif, uyumlu',
                'strengths': 'Adalet duygusu, diplomasi, uyum yaratma, estetik, objektiflik',
                'weaknesses': 'Kararsızlık, çatışmadan kaçınma, yüzeysellik, bağımlılık',
                'compatibility': 'İkizler, Kova, Aslan, Yay',
                'lucky_numbers': '6, 9',
                'lucky_colors': 'Mavi, Pembe',
                'lucky_day': 'Cuma',
                'order': 7,
            },
            {
                'name': 'Akrep',
                'name_en': 'Scorpio',
                'slug': 'akrep',
                'symbol': '♏',
                'element': 'water',
                'quality': 'fixed',
                'ruling_planet': 'Plüton',
                'date_range': '23 Ekim - 21 Kasım',
                'start_month': 10,
                'start_day': 23,
                'end_month': 11,
                'end_day': 21,
                'description': 'Akrep burcu tutkulu, gizemli ve güçlü bireylerdir. Derin duygusal bağlar kurar ve dönüşümden korkmaz.',
                'traits': 'Tutkulu, gizemli, güçlü, kararlı, sadık, sezgisel',
                'strengths': 'Tutku, kararlılık, sadakat, sezgi, derinlik',
                'weaknesses': 'Kıskançlık, intikam alma, aşırı kontrol, saplantı',
                'compatibility': 'Yengeç, Balık, Boğa, Başak',
                'lucky_numbers': '8, 9',
                'lucky_colors': 'Bordo, Siyah',
                'lucky_day': 'Salı',
                'order': 8,
            },
            {
                'name': 'Yay',
                'name_en': 'Sagittarius',
                'slug': 'yay',
                'symbol': '♐',
                'element': 'fire',
                'quality': 'mutable',
                'ruling_planet': 'Jüpiter',
                'date_range': '22 Kasım - 21 Aralık',
                'start_month': 11,
                'start_day': 22,
                'end_month': 12,
                'end_day': 21,
                'description': 'Yay burcu iyimser, özgür ruhlu ve maceraperest bireylerdir. Bilgiye ve yeni deneyimlere açıktırlar.',
                'traits': 'İyimser, özgür, maceracı, dürüst, felsefik, neşeli',
                'strengths': 'İyimserlik, macera ruhu, dürüstlük, bilge, özgürlük',
                'weaknesses': 'Sorumsuzluk, dikkatsizlik, aşırı dürüstlük, sabırsızlık',
                'compatibility': 'Koç, Aslan, Terazi, Kova',
                'lucky_numbers': '3, 9',
                'lucky_colors': 'Mor, Lacivert',
                'lucky_day': 'Perşembe',
                'order': 9,
            },
            {
                'name': 'Oğlak',
                'name_en': 'Capricorn',
                'slug': 'oglak',
                'symbol': '♑',
                'element': 'earth',
                'quality': 'cardinal',
                'ruling_planet': 'Satürn',
                'date_range': '22 Aralık - 19 Ocak',
                'start_month': 12,
                'start_day': 22,
                'end_month': 1,
                'end_day': 19,
                'description': 'Oğlak burcu disiplinli, hırslı ve sorumlu bireylerdir. Başarıya odaklı ve sabırlı çalışırlar.',
                'traits': 'Disiplinli, hırslı, sorumlu, sabırlı, gerçekçi, geleneksel',
                'strengths': 'Disiplin, sorumluluk, azim, gerçekçilik, organizasyon',
                'weaknesses': 'Katılık, aşırı ciddiyetlik, karamsarlık, baskıcılık',
                'compatibility': 'Boğa, Başak, Akrep, Balık',
                'lucky_numbers': '8, 10',
                'lucky_colors': 'Siyah, Kahverengi',
                'lucky_day': 'Cumartesi',
                'order': 10,
            },
            {
                'name': 'Kova',
                'name_en': 'Aquarius',
                'slug': 'kova',
                'symbol': '♒',
                'element': 'air',
                'quality': 'fixed',
                'ruling_planet': 'Uranüs',
                'date_range': '20 Ocak - 18 Şubat',
                'start_month': 1,
                'start_day': 20,
                'end_month': 2,
                'end_day': 18,
                'description': 'Kova burcu orijinal, bağımsız ve insancıl bireylerdir. Yenilikçi fikirlere ve özgürlüğe değer verirler.',
                'traits': 'Orijinal, bağımsız, insancıl, entellektüel, vizyoner, yenilikçi',
                'strengths': 'Orijinallik, bağımsızlık, insancıllık, zeka, ileriyi görme',
                'weaknesses': 'Mesafelilik, inatçılık, aşırı idealleştirme, duygusal soğukluk',
                'compatibility': 'İkizler, Terazi, Koç, Yay',
                'lucky_numbers': '4, 11',
                'lucky_colors': 'Turkuaz, Elektrik Mavisi',
                'lucky_day': 'Cumartesi',
                'order': 11,
            },
            {
                'name': 'Balık',
                'name_en': 'Pisces',
                'slug': 'balik',
                'symbol': '♓',
                'element': 'water',
                'quality': 'mutable',
                'ruling_planet': 'Neptün',
                'date_range': '19 Şubat - 20 Mart',
                'start_month': 2,
                'start_day': 19,
                'end_month': 3,
                'end_day': 20,
                'description': 'Balık burcu empatik, sezgisel ve yaratıcı bireylerdir. Ruhsal derinlikleri ve hayal güçleri güçlüdür.',
                'traits': 'Empatik, sezgisel, yaratıcı, şefkatli, romantik, ruhsal',
                'strengths': 'Empati, sezgi, yaratıcılık, şefkat, anlayış',
                'weaknesses': 'Aşırı duygusallık, kaçışçılık, kurban rolü, sınır koyamama',
                'compatibility': 'Yengeç, Akrep, Boğa, Oğlak',
                'lucky_numbers': '3, 7',
                'lucky_colors': 'Deniz Yeşili, Mor',
                'lucky_day': 'Perşembe',
                'order': 12,
            },
        ]

        created_count = 0
        updated_count = 0

        for data in zodiac_data:
            sign, created = ZodiacSign.objects.get_or_create(
                slug=data['slug'],
                defaults=data
            )
            
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'✓ {data["name"]} ({data["name_en"]}) oluşturuldu'))
            else:
                # Update existing sign
                for key, value in data.items():
                    setattr(sign, key, value)
                sign.save()
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'↻ {data["name"]} ({data["name_en"]}) güncellendi'))

        self.stdout.write(self.style.SUCCESS(f'\n✅ Toplam: {created_count} burç oluşturuldu, {updated_count} burç güncellendi'))
        self.stdout.write(self.style.SUCCESS(f'📊 Veritabanında toplam {ZodiacSign.objects.count()} burç bulunuyor'))
