from django.core.management.base import BaseCommand
from zodiac.models import ZodiacSign


class Command(BaseCommand):
    help = '12 burcun temel verilerini veritabanına ekler'

    def handle(self, *args, **options):
        zodiac_data = [
            {
                'name': 'Koç',
                'name_en': 'Aries',
                'slug': 'koc',
                'symbol': '♈',
                'element': 'fire',
                'quality': 'cardinal',
                'ruling_planet': 'Mars',
                'start_month': 3,
                'start_day': 21,
                'end_month': 4,
                'end_day': 19,
                'description': 'Koç burcu, zodyak kuşağının ilk işaretidir ve yeni başlangıçları, enerjinin patlamasını ve cesaretin simgesini temsil eder. Mars gezegeni tarafından yönetilen Koç burcu, liderlik özellikleri, girişkenlik ve bağımsızlık tutkusuyla tanınır.',
                'traits': 'Cesur, kararlı, kendine güvenli, tutkulu, iyimser, dürüst, hareketli, rekabetçi, bağımsız',
                'strengths': 'Cesur, kararlı, kendine güvenli, tutkulu, iyimser, dürüst',
                'weaknesses': 'Sabırsız, huysuz, kısa ömürlü, saldırgan, düşüncesiz',
                'lucky_numbers': '1, 8, 17',
                'lucky_colors': 'Kırmızı',
                'lucky_day': 'Salı',
                'compatibility': 'Aslan, Yay, İkizler, Kova',
                'order': 1,
            },
            {
                'name': 'Boğa',
                'name_en': 'Taurus',
                'slug': 'boga',
                'symbol': '♉',
                'element': 'earth',
                'quality': 'fixed',
                'ruling_planet': 'Venüs',
                'start_month': 4,
                'start_day': 20,
                'end_month': 5,
                'end_day': 20,
                'description': 'Boğa burcu, güvenilirlik, pratiklik ve sağlamlık sembolüdür. Venüs gezegeni tarafından yönetilen Boğa burcu, güzellik, konfor ve maddi güvenlik arayışıyla karakterize edilir. Sabırlı, kararlı ve sadık bir burçtur.',
                'traits': 'Güvenilir, sabırlı, pratik, sadık, sorumlu, kararlı, sakin, zevk düşkünü',
                'strengths': 'Güvenilir, sabırlı, pratik, sadık, sorumlu, kararlı',
                'weaknesses': 'İnatçı, sahiplenici, aşırı materyalist, tembelliğe meyilli',
                'lucky_numbers': '2, 6, 9, 12, 24',
                'lucky_colors': 'Yeşil, Pembe',
                'lucky_day': 'Cuma, Pazartesi',
                'compatibility': 'Başak, Oğlak, Yengeç, Balık',
                'order': 2,
            },
            {
                'name': 'İkizler',
                'name_en': 'Gemini',
                'slug': 'ikizler',
                'symbol': '♊',
                'element': 'air',
                'quality': 'mutable',
                'ruling_planet': 'Merkür',
                'start_month': 5,
                'start_day': 21,
                'end_month': 6,
                'end_day': 20,
                'description': 'İkizler burcu, iletişim, zeka ve çok yönlülüğün simgesidir. Merkür tarafından yönetilen İkizler, meraklı, uyumlu ve sosyal bir burçtur. İki yüzlülük değil, çok yönlülük İkizlerin en belirgin özelliğidir.',
                'traits': 'Nazik, sevecen, meraklı, uyumlu, yetenekli, zeki, sosyal, konuşkan',
                'strengths': 'Nazik, sevecen, meraklı, uyumlu, yetenekli iletişimci',
                'weaknesses': 'Gergin, tutarsız, kararsız, yüzeysel ilişkiler kurma eğilimi',
                'lucky_numbers': '5, 7, 14, 23',
                'lucky_colors': 'Sarı, Açık Yeşil',
                'lucky_day': 'Çarşamba',
                'compatibility': 'Terazi, Kova, Koç, Aslan',
                'order': 3,
            },
            {
                'name': 'Yengeç',
                'name_en': 'Cancer',
                'slug': 'yengec',
                'symbol': '♋',
                'element': 'water',
                'quality': 'cardinal',
                'ruling_planet': 'Ay',
                'start_month': 6,
                'start_day': 21,
                'end_month': 7,
                'end_day': 22,
                'description': 'Yengeç burcu, duyarlılık, sezgi ve koruyuculuğun sembolüdür. Ay tarafından yönetilen Yengeç, duygusal derinliği, aile bağları ve güçlü bir hafızayla tanınır. Empatik ve sevgi dolu bir burçtur.',
                'traits': 'Sadık, duygusal, sempatik, ikna edici, bağışlayıcı, koruyucu, sezgisel',
                'strengths': 'Sadık, duygusal, ikna edici, bağışlayıcı, koruyucu',
                'weaknesses': 'Aşırı duygusal, güvensiz, savunmacı, manipülatif, pesimist',
                'lucky_numbers': '2, 3, 15, 20',
                'lucky_colors': 'Beyaz',
                'lucky_day': 'Pazartesi, Perşembe',
                'compatibility': 'Akrep, Balık, Boğa, Başak',
                'order': 4,
            },
            {
                'name': 'Aslan',
                'name_en': 'Leo',
                'slug': 'aslan',
                'symbol': '♌',
                'element': 'fire',
                'quality': 'fixed',
                'ruling_planet': 'Güneş',
                'start_month': 7,
                'start_day': 23,
                'end_month': 8,
                'end_day': 22,
                'description': 'Aslan burcu, liderlik, yaratıcılık ve cömertliğin simgesidir. Güneş tarafından yönetilen Aslan, dramatik, tutkulu ve güçlü bir varlık sergiler. Doğal liderler olan Aslanlar, sahne ışıklarını sever.',
                'traits': 'Yaratıcı, tutkulu, cömert, sıcak kalpli, neşeli, mizah sevgisi, lider',
                'strengths': 'Yaratıcı, tutkulu, cömert, sıcak kalpli, neşeli, mizah sevgisi',
                'weaknesses': 'Kibirli, inatçı, bencil, tembel, esnek olmayan',
                'lucky_numbers': '1, 3, 10, 19',
                'lucky_colors': 'Altın, Turuncu, Sarı',
                'lucky_day': 'Pazar',
                'compatibility': 'Koç, Yay, İkizler, Terazi',
                'order': 5,
            },
            {
                'name': 'Başak',
                'name_en': 'Virgo',
                'slug': 'basak',
                'symbol': '♍',
                'element': 'earth',
                'quality': 'mutable',
                'ruling_planet': 'Merkür',
                'start_month': 8,
                'start_day': 23,
                'end_month': 9,
                'end_day': 22,
                'description': 'Başak burcu, analitik düşünce, pratiklik ve mükemmeliyetçiliğin simgesidir. Merkür tarafından yönetilen Başak, detaylara dikkat, organizasyon ve yardımseverlikle tanınır. Sistemli ve titiz bir burçtur.',
                'traits': 'Sadık, analitik, nazik, çalışkan, pratik, titiz, mütevazı, hizmet odaklı',
                'strengths': 'Sadık, analitik, nazik, çalışkan, pratik',
                'weaknesses': 'Aşırı eleştirel, endişeli, aşırı titiz, muhafazakar, perfeksiyonist',
                'lucky_numbers': '5, 14, 15, 23, 32',
                'lucky_colors': 'Gri, Bej, Soluk Sarı',
                'lucky_day': 'Çarşamba',
                'compatibility': 'Boğa, Oğlak, Yengeç, Akrep',
                'order': 6,
            },
            {
                'name': 'Terazi',
                'name_en': 'Libra',
                'slug': 'terazi',
                'symbol': '♎',
                'element': 'air',
                'quality': 'cardinal',
                'ruling_planet': 'Venüs',
                'start_month': 9,
                'start_day': 23,
                'end_month': 10,
                'end_day': 22,
                'description': 'Terazi burcu, denge, adalet ve uyumun simgesidir. Venüs tarafından yönetilen Terazi, estetik, diplomasi ve ilişkilere verilen önemle karakterize edilir. Barışçıl ve sosyal bir burçtur.',
                'traits': 'Diplomatik, nazik, adil, sosyal, işbirlikçi, dengeli, sanat sevgisi',
                'strengths': 'Diplomatik, nazik, adil, sosyal, işbirlikçi',
                'weaknesses': 'Kararsız, çatışmadan kaçınma, kendine acıma, aşırı uysal',
                'lucky_numbers': '4, 6, 13, 15, 24',
                'lucky_colors': 'Pembe, Yeşil',
                'lucky_day': 'Cuma',
                'compatibility': 'İkizler, Kova, Aslan, Yay',
                'order': 7,
            },
            {
                'name': 'Akrep',
                'name_en': 'Scorpio',
                'slug': 'akrep',
                'symbol': '♏',
                'element': 'water',
                'quality': 'fixed',
                'ruling_planet': 'Plüton, Mars',
                'start_month': 10,
                'start_day': 23,
                'end_month': 11,
                'end_day': 21,
                'description': 'Akrep burcu, tutku, dönüşüm ve güçlü sezgilerin simgesidir. Plüton ve Mars tarafından yönetilen Akrep, yoğunluk, gizem ve derin duygusal bağlarla tanınır. Kararlı ve manyetik bir burçtur.',
                'traits': 'İhtiraslı, inatçı, sadık, cesur, tutkulu, gerçekçi, gizemli, manyetik',
                'strengths': 'İhtiraslı, inatçı, sadık, cesur, gerçekçi',
                'weaknesses': 'Kıskanç, gizli, şüpheci, manipülatif, intikamcı',
                'lucky_numbers': '8, 11, 18, 22',
                'lucky_colors': 'Kırmızı, Turuncu',
                'lucky_day': 'Salı',
                'compatibility': 'Yengeç, Balık, Başak, Oğlak',
                'order': 8,
            },
            {
                'name': 'Yay',
                'name_en': 'Sagittarius',
                'slug': 'yay',
                'symbol': '♐',
                'element': 'fire',
                'quality': 'mutable',
                'ruling_planet': 'Jüpiter',
                'start_month': 11,
                'start_day': 22,
                'end_month': 12,
                'end_day': 21,
                'description': 'Yay burcu, özgürlük, macera ve iyimserliğin simgesidir. Jüpiter tarafından yönetilen Yay, filozof ruhu, açık sözlülük ve sürekli öğrenme arzusuyla tanınır. Neşeli ve hareketli bir burçtur.',
                'traits': 'Cömert, idealist, anlayışlı, dürüst, iyimser, özgürlük sever, maceraperest',
                'strengths': 'Cömert, idealist, anlayışlı, dürüst, iyimser',
                'weaknesses': 'Düşüncesiz, sabırsız, taktik yoksunluğu, aşırı açık sözlü',
                'lucky_numbers': '3, 7, 9, 12, 21',
                'lucky_colors': 'Mavi',
                'lucky_day': 'Perşembe',
                'compatibility': 'Koç, Aslan, Terazi, Kova',
                'order': 9,
            },
            {
                'name': 'Oğlak',
                'name_en': 'Capricorn',
                'slug': 'oglak',
                'symbol': '♑',
                'element': 'earth',
                'quality': 'cardinal',
                'ruling_planet': 'Satürn',
                'start_month': 12,
                'start_day': 22,
                'end_month': 1,
                'end_day': 19,
                'description': 'Oğlak burcu, disiplin, sorumluluk ve başarı azmiyle simgelenir. Satürn tarafından yönetilen Oğlak, pratiklik, geleneksellik ve uzun vadeli hedeflere odaklanmayla tanınır. Kararlı ve çalışkan bir burçtur.',
                'traits': 'Sorumlu, disiplinli, özdenetimli, pratik, ciddi, bağımsız, geleneksel',
                'strengths': 'Sorumlu, disiplinli, özdenetimli, pratik, ciddi',
                'weaknesses': 'Her şeyi bilen, bağışlamaz, kötümser, acımasız',
                'lucky_numbers': '4, 8, 13, 22',
                'lucky_colors': 'Kahverengi, Siyah',
                'lucky_day': 'Cumartesi',
                'compatibility': 'Boğa, Başak, Akrep, Balık',
                'order': 10,
            },
            {
                'name': 'Kova',
                'name_en': 'Aquarius',
                'slug': 'kova',
                'symbol': '♒',
                'element': 'air',
                'quality': 'fixed',
                'ruling_planet': 'Uranüs, Satürn',
                'start_month': 1,
                'start_day': 20,
                'end_month': 2,
                'end_day': 18,
                'description': 'Kova burcu, orijinallik, bağımsızlık ve insancıllığın simgesidir. Uranüs tarafından yönetilen Kova, yenilikçilik, özgünlük ve toplum yararına çalışmayla tanınır. Vizyoner ve alışılmadık bir burçtur.',
                'traits': 'İlerici, orijinal, bağımsız, insancıl, arkadaş canlısı, entelektüel, vizyoner',
                'strengths': 'İlerici, orijinal, bağımsız, insancıl, entelektüel',
                'weaknesses': 'Duygusal ifadeden kaçınma, temperamental, uzlaşmaz, aloof',
                'lucky_numbers': '4, 7, 11, 22, 29',
                'lucky_colors': 'Açık Mavi, Gümüş',
                'lucky_day': 'Cumartesi',
                'compatibility': 'İkizler, Terazi, Koç, Yay',
                'order': 11,
            },
            {
                'name': 'Balık',
                'name_en': 'Pisces',
                'slug': 'balik',
                'symbol': '♓',
                'element': 'water',
                'quality': 'mutable',
                'ruling_planet': 'Neptün, Jüpiter',
                'start_month': 2,
                'start_day': 19,
                'end_month': 3,
                'end_day': 20,
                'description': 'Balık burcu, sezgi, hayal gücü ve merhamet simgesidir. Neptün tarafından yönetilen Balık, sanatsal yetenekler, spiritüel eğilim ve derin duygusallıkla tanınır. Empatik ve romantik bir burçtur.',
                'traits': 'Şefkatli, sanatsal, sezgisel, nazik, bilge, müzikal, romantik, hayal gücü',
                'strengths': 'Şefkatli, sanatsal, sezgisel, nazik, bilge, müzikal',
                'weaknesses': 'Aşırı güvenme, üzgün, gerçeklikten kaçma arzusu, kurban rolü, tembellik',
                'lucky_numbers': '3, 9, 12, 15, 18, 24',
                'lucky_colors': 'Deniz Yeşili, Mor',
                'lucky_day': 'Perşembe',
                'compatibility': 'Yengeç, Akrep, Boğa, Oğlak',
                'order': 12,
            },
        ]

        created_count = 0
        updated_count = 0

        for data in zodiac_data:
            sign, created = ZodiacSign.objects.update_or_create(
                slug=data['slug'],
                defaults=data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'✅ {sign.name} burcu oluşturuldu')
                )
            else:
                updated_count += 1
                self.stdout.write(
                    self.style.WARNING(f'⚠️  {sign.name} burcu güncellendi')
                )

        self.stdout.write(
            self.style.SUCCESS(
                f'\n🎉 İşlem tamamlandı! {created_count} burç oluşturuldu, {updated_count} burç güncellendi.'
            )
        )
