# Generated by Django 5.0.2 on 2025-10-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('zodiac', '0004_userdailyhoroscope_usermonthlyhoroscope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zodiac_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zodiac.zodiacsign', verbose_name='Burç'),
        ),
    ]
