# Generated by Django 5.0.2 on 2025-10-21 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_zodiac_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Yanıtlandı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('document_type', models.CharField(choices=[('terms', 'Kullanım Koşulları'), ('privacy', 'Gizlilik Politikası'), ('cookies', 'Çerez Politikası'), ('kvkk', 'KVKK Aydınlatma Metni')], max_length=20, unique=True, verbose_name='Belge Tipi')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versiyon')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Yürürlük Tarihi')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Yasal Belge',
                'verbose_name_plural': 'Yasal Belgeler',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('reason', models.TextField(blank=True, verbose_name='Sebep')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Yönetici Notları')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deletions', to=settings.AUTH_USER_MODEL, verbose_name='İşleyen Yetkili')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Veri Silme Talebi',
                'verbose_name_plural': 'Veri Silme Talepleri',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_version', models.CharField(max_length=20, verbose_name='Belge Versiyonu')),
                ('consent_given', models.BooleanField(default=True, verbose_name='Onay Verildi')),
                ('consent_date', models.DateTimeField(auto_now_add=True, verbose_name='Onay Tarihi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.legaldocument', verbose_name='Belge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Onayı',
                'verbose_name_plural': 'Kullanıcı Onayları',
                'ordering': ['-consent_date'],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
