# Generated by Django 5.0.2 on 2025-10-21 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactmessage_legaldocument_datadeletionrequest_and_more'),
        ('tarot', '0012_alter_herosection_primary_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('token_amount', models.IntegerField(verbose_name='Jeton Sayısı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (USD)')),
                ('bonus_tokens', models.IntegerField(default=0, help_text='Ekstra verilen jeton', verbose_name='Bonus Jeton')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('display_order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jeton Paketi',
                'verbose_name_plural': 'Jeton Paketleri',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium Üye'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=10, help_text='Premium hizmetler için kullanılır', verbose_name='Jeton Sayısı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_reading_limit',
            field=models.IntegerField(default=1, verbose_name='Günlük Ücretsiz Okuma Limiti'),
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Satın Alma'), ('usage', 'Kullanım'), ('bonus', 'Bonus'), ('refund', 'İade'), ('admin', 'Admin İşlemi')], max_length=20, verbose_name='İşlem Tipi')),
                ('amount', models.IntegerField(help_text='Pozitif: ekleme, Negatif: kullanım', verbose_name='Jeton Miktarı')),
                ('balance_before', models.IntegerField(verbose_name='Önceki Bakiye')),
                ('balance_after', models.IntegerField(verbose_name='Sonraki Bakiye')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarot.tarotreading', verbose_name='İlgili Okuma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Jeton İşlemi',
                'verbose_name_plural': 'Jeton İşlemleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
