# Generated by Django 5.0.2 on 2025-10-14 14:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='fa-shopping-bag', help_text='Örnek: fa-gem, fa-star, fa-ring', max_length=50, verbose_name='İkon (Font Awesome)')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Resim URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Oturum Anahtarı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sepet',
                'verbose_name_plural': 'Sepetler',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Sipariş No')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('preparing', 'Hazırlanıyor'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(verbose_name='Adres')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Posta Kodu')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ara Toplam')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Kargo Ücreti')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Kapıda Ödeme'), ('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Havale/EFT')], default='cash_on_delivery', max_length=20, verbose_name='Ödeme Yöntemi')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Sipariş Notu')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('short_description', models.CharField(blank=True, max_length=250, verbose_name='Kısa Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İndirimli Fiyat')),
                ('discount_percentage', models.IntegerField(blank=True, default=0, verbose_name='İndirim %')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok Miktarı')),
                ('stock_status', models.CharField(choices=[('in_stock', 'Stokta'), ('low_stock', 'Stok Az'), ('out_of_stock', 'Stok Yok'), ('pre_order', 'Ön Sipariş')], default='in_stock', max_length=20, verbose_name='Stok Durumu')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Ana Resim URL')),
                ('image_2', models.URLField(blank=True, null=True, verbose_name='Resim 2 URL')),
                ('image_3', models.URLField(blank=True, null=True, verbose_name='Resim 3 URL')),
                ('features', models.TextField(blank=True, help_text='Her satıra bir özellik yazın', verbose_name='Özellikler (Her satıra bir özellik)')),
                ('zodiac_signs', models.CharField(blank=True, help_text='Örnek: Koç, Aslan, Yay', max_length=200, verbose_name='Uygun Burçlar')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('views', models.IntegerField(default=0, verbose_name='Görüntülenme')),
                ('sales_count', models.IntegerField(default=0, verbose_name='Satış Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('quantity', models.IntegerField(verbose_name='Adet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Ürünü',
                'verbose_name_plural': 'Sipariş Ürünleri',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Adet')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Sepet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sepet Ürünü',
                'verbose_name_plural': 'Sepet Ürünleri',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
