# Generated by Django 5.0.2 on 2025-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_cost_price_product_eprolo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='auto_activate_products',
            field=models.BooleanField(default=False, help_text="EPROLO'dan gelen ürünler otomatik olarak aktif edilsin mi?", verbose_name='Ürünleri Otomatik Aktif Et'),
        ),
        migrations.AddField(
            model_name='category',
            name='custom_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu kategori için özel kar marjı (boş bırakılırsa genel ayar kullanılır)', max_digits=5, null=True, verbose_name='Özel Kar Marjı %'),
        ),
        migrations.AddField(
            model_name='category',
            name='enable_eprolo_sync',
            field=models.BooleanField(default=False, help_text='Bu kategoriye EPROLO ürünleri senkronize edilsin mi?', verbose_name='EPROLO Senkronizasyonu'),
        ),
        migrations.AddField(
            model_name='category',
            name='eprolo_category_id',
            field=models.CharField(blank=True, help_text="EPROLO'daki kategori ID veya adı", max_length=100, null=True, verbose_name='EPROLO Kategori ID'),
        ),
        migrations.AddField(
            model_name='category',
            name='eprolo_category_name',
            field=models.CharField(blank=True, help_text="EPROLO'daki kategori adı (örn: Electronics, Fashion, Home)", max_length=200, null=True, verbose_name='EPROLO Kategori Adı'),
        ),
    ]
