# Generated by Django 5.0.2 on 2025-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_auto_activate_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opsiyonel: USD fiyat', max_digits=10, null=True, verbose_name='Fiyat (USD)'),
        ),
    ]
