# Generated by Django 5.0.2 on 2025-10-27 10:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_price_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintifySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('products', 'Ürün Senkronizasyonu'), ('stock', 'Stok Senkronizasyonu'), ('orders', 'Sipariş Senkronizasyonu'), ('webhooks', 'Webhook Senkronizasyonu')], max_length=20, verbose_name='Senkronizasyon Türü')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Süre (saniye)')),
                ('total_items', models.IntegerField(default=0, verbose_name='Toplam Öğe')),
                ('successful_items', models.IntegerField(default=0, verbose_name='Başarılı Öğe')),
                ('failed_items', models.IntegerField(default=0, verbose_name='Başarısız Öğe')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('log_data', models.JSONField(blank=True, null=True, verbose_name='Detaylı Log')),
            ],
            options={
                'verbose_name': 'Printify Sync Log',
                'verbose_name_plural': 'Printify Sync Logları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='enable_printify_sync',
            field=models.BooleanField(default=False, help_text='Bu kategoriye Printify ürünleri senkronize edilsin mi?', verbose_name='Printify Senkronizasyonu'),
        ),
        migrations.AddField(
            model_name='category',
            name='printify_auto_activate',
            field=models.BooleanField(default=False, help_text="Printify'dan gelen ürünler otomatik olarak aktif edilsin mi?", verbose_name='Printify Ürünleri Otomatik Aktif Et'),
        ),
        migrations.AddField(
            model_name='category',
            name='printify_category_mapping',
            field=models.JSONField(blank=True, help_text='Printify kategorileri ile eşleştirme bilgileri', null=True, verbose_name='Printify Kategori Eşleştirme'),
        ),
        migrations.AddField(
            model_name='category',
            name='printify_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Printify ürünleri için özel kar marjı', max_digits=5, null=True, verbose_name='Printify Kar Marjı %'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_blueprint_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Printify Blueprint ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_data',
            field=models.JSONField(blank=True, help_text="Printify'dan gelen ham JSON verisi", null=True, verbose_name='Printify Ham Veri'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Printify Senkronizasyonu'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_print_provider_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Printify Baskı Sağlayıcı ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Printify Ürün ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_shop_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Printify Mağaza ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Printify Durum'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_variant_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Printify Varyant ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuel Eklendi'), ('eprolo', 'EPROLO'), ('printify', 'Printify')], default='manual', max_length=20, verbose_name='Kaynak'),
        ),
        migrations.CreateModel(
            name='PrintifySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(blank=True, help_text='Printify API token', max_length=500, verbose_name='API Token')),
                ('shop_id', models.CharField(blank=True, help_text='Printify shop ID', max_length=100, verbose_name='Shop ID')),
                ('use_sandbox', models.BooleanField(default=True, help_text='Test ortamı için sandbox kullan', verbose_name='Sandbox Modu')),
                ('default_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Varsayılan Kar Marjı %')),
                ('auto_update_prices', models.BooleanField(default=False, verbose_name='Fiyatları Otomatik Güncelle')),
                ('usd_to_try_rate', models.DecimalField(decimal_places=2, default=Decimal('34.50'), max_digits=6, verbose_name='USD/TL Kuru')),
                ('auto_import_products', models.BooleanField(default=False, verbose_name='Ürünleri Otomatik İçe Aktar')),
                ('auto_publish_products', models.BooleanField(default=False, verbose_name='Ürünleri Otomatik Yayınla')),
                ('auto_submit_orders', models.BooleanField(default=False, verbose_name='Siparişleri Otomatik Gönder')),
                ('order_status_for_auto_submit', models.CharField(default='confirmed', max_length=20, verbose_name='Otomatik Gönderim İçin Sipariş Durumu')),
                ('webhook_url', models.URLField(blank=True, help_text='Printify webhook eventi için URL', verbose_name='Webhook URL')),
                ('webhook_secret', models.CharField(blank=True, max_length=200, verbose_name='Webhook Secret')),
                ('last_product_sync', models.DateTimeField(blank=True, null=True, verbose_name='Son Ürün Senkronizasyonu')),
                ('last_order_sync', models.DateTimeField(blank=True, null=True, verbose_name='Son Sipariş Senkronizasyonu')),
                ('sync_interval_hours', models.IntegerField(default=24, verbose_name='Senkronizasyon Aralığı (saat)')),
                ('notify_on_sync_complete', models.BooleanField(default=True, verbose_name='Senkronizasyon Tamamlandığında Bildir')),
                ('notify_on_sync_error', models.BooleanField(default=True, verbose_name='Senkronizasyon Hatasında Bildir')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Bildirim E-postası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('default_category', models.ForeignKey(blank=True, help_text='Printify ürünleri için varsayılan kategori', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Varsayılan Kategori')),
            ],
            options={
                'verbose_name': 'Printify Ayarları',
                'verbose_name_plural': 'Printify Ayarları',
            },
        ),
    ]
