# Generated by Django 5.0.2 on 2025-10-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_price_usd'),
        ('shop', '0005_printifysynclog_category_enable_printify_sync_and_more'),
    ]

    operations = [
    ]