# Generated by Django 5.0.2 on 2025-10-06 11:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Burç Adı')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='İngilizce Adı')),
                ('symbol', models.CharField(max_length=10, verbose_name='Sembol')),
                ('element', models.CharField(choices=[('fire', 'Ateş'), ('earth', 'Toprak'), ('air', 'Hava'), ('water', 'Su')], max_length=20, verbose_name='Element')),
                ('quality', models.CharField(choices=[('cardinal', 'Öncü'), ('fixed', 'Sabit'), ('mutable', 'Değişken')], max_length=20, verbose_name='Nitelik')),
                ('ruling_planet', models.CharField(max_length=50, verbose_name='Yöneten Gezegen')),
                ('date_range', models.CharField(max_length=50, verbose_name='Tarih Aralığı')),
                ('start_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Başlangıç Ayı')),
                ('start_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Başlangıç Günü')),
                ('end_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Bitiş Ayı')),
                ('end_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Bitiş Günü')),
                ('description', models.TextField(verbose_name='Genel Açıklama')),
                ('traits', models.TextField(verbose_name='Karakteristik Özellikleri')),
                ('strengths', models.TextField(verbose_name='Güçlü Yönleri')),
                ('weaknesses', models.TextField(verbose_name='Zayıf Yönleri')),
                ('compatibility', models.TextField(verbose_name='Uyumlu Burçlar')),
                ('lucky_numbers', models.CharField(max_length=100, verbose_name='Şanslı Sayılar')),
                ('lucky_colors', models.CharField(max_length=100, verbose_name='Şanslı Renkler')),
                ('lucky_day', models.CharField(max_length=20, verbose_name='Şanslı Gün')),
                ('image_url', models.URLField(blank=True, verbose_name='Görsel URL')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Burç',
                'verbose_name_plural': 'Burçlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uyum Skoru')),
                ('love_compatibility', models.TextField(verbose_name='Aşk Uyumu')),
                ('friendship_compatibility', models.TextField(verbose_name='Arkadaşlık Uyumu')),
                ('work_compatibility', models.TextField(verbose_name='İş Uyumu')),
                ('challenges', models.TextField(verbose_name='Olası Zorluklar')),
                ('advice', models.TextField(verbose_name='Tavsiyeler')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='gemini', max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('sign1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_sign1', to='zodiac.zodiacsign', verbose_name='İlk Burç')),
                ('sign2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_sign2', to='zodiac.zodiacsign', verbose_name='İkinci Burç')),
            ],
            options={
                'verbose_name': 'Burç Uyumu Analizi',
                'verbose_name_plural': 'Burç Uyumu Analizleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('birth_time', models.TimeField(verbose_name='Doğum Saati')),
                ('birth_place', models.CharField(max_length=200, verbose_name='Doğum Yeri')),
                ('latitude', models.FloatField(verbose_name='Enlem')),
                ('longitude', models.FloatField(verbose_name='Boylam')),
                ('personality_analysis', models.TextField(verbose_name='Kişilik Analizi')),
                ('emotional_analysis', models.TextField(verbose_name='Duygusal Analiz')),
                ('career_analysis', models.TextField(verbose_name='Kariyer Analizi')),
                ('relationship_analysis', models.TextField(verbose_name='İlişki Analizi')),
                ('life_path_analysis', models.TextField(verbose_name='Yaşam Yolu Analizi')),
                ('planet_positions', models.JSONField(default=dict, verbose_name='Gezegen Pozisyonları')),
                ('house_positions', models.JSONField(default=dict, verbose_name='Ev Pozisyonları')),
                ('aspects', models.JSONField(default=dict, verbose_name='Açılar (Aspects)')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='gemini', max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('moon_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_chart_moon', to='zodiac.zodiacsign', verbose_name='Ay Burcu')),
                ('rising_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_chart_rising', to='zodiac.zodiacsign', verbose_name='Yükselen Burç')),
                ('sun_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_chart_sun', to='zodiac.zodiacsign', verbose_name='Güneş Burcu')),
            ],
            options={
                'verbose_name': 'Doğum Haritası',
                'verbose_name_plural': 'Doğum Haritaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Hafta Başlangıcı')),
                ('week_end', models.DateField(verbose_name='Hafta Bitişi')),
                ('general', models.TextField(verbose_name='Genel Yorum')),
                ('love', models.TextField(verbose_name='Aşk Hayatı')),
                ('career', models.TextField(verbose_name='Kariyer')),
                ('health', models.TextField(verbose_name='Sağlık')),
                ('money', models.TextField(verbose_name='Finans')),
                ('advice', models.TextField(verbose_name='Haftalık Tavsiye')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='gemini', max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zodiac_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zodiac.zodiacsign', verbose_name='Burç')),
            ],
            options={
                'verbose_name': 'Haftalık Burç Yorumu',
                'verbose_name_plural': 'Haftalık Burç Yorumları',
                'ordering': ['-week_start'],
                'unique_together': {('zodiac_sign', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Ay')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('general', models.TextField(verbose_name='Genel Yorum')),
                ('love', models.TextField(verbose_name='Aşk Hayatı')),
                ('career', models.TextField(verbose_name='Kariyer')),
                ('health', models.TextField(verbose_name='Sağlık')),
                ('money', models.TextField(verbose_name='Finans')),
                ('opportunities', models.TextField(verbose_name='Fırsatlar')),
                ('challenges', models.TextField(verbose_name='Zorluklar')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='gemini', max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zodiac_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zodiac.zodiacsign', verbose_name='Burç')),
            ],
            options={
                'verbose_name': 'Aylık Burç Yorumu',
                'verbose_name_plural': 'Aylık Burç Yorumları',
                'ordering': ['-year', '-month'],
                'unique_together': {('zodiac_sign', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DailyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('general', models.TextField(verbose_name='Genel Yorum')),
                ('love', models.TextField(verbose_name='Aşk Hayatı')),
                ('career', models.TextField(verbose_name='Kariyer')),
                ('health', models.TextField(verbose_name='Sağlık')),
                ('money', models.TextField(verbose_name='Finans')),
                ('mood_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Ruh Hali Skoru')),
                ('lucky_number', models.IntegerField(verbose_name='Günün Şanslı Sayısı')),
                ('lucky_color', models.CharField(max_length=50, verbose_name='Günün Şanslı Rengi')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='gemini', max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zodiac_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zodiac.zodiacsign', verbose_name='Burç')),
            ],
            options={
                'verbose_name': 'Günlük Burç Yorumu',
                'verbose_name_plural': 'Günlük Burç Yorumları',
                'ordering': ['-date'],
                'unique_together': {('zodiac_sign', 'date')},
            },
        ),
    ]
