# Generated by Django 5.0.2 on 2025-10-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacsign',
            name='slug',
            field=models.SlugField(default='default', unique=True, verbose_name='Slug'),
        ),
    ]
