# Generated by Django 5.0.2 on 2025-10-06 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0002_zodiacsign_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('birth_time', models.TimeField(verbose_name='Doğum Saati')),
                ('birth_place', models.CharField(max_length=200, verbose_name='Doğum Yeri')),
                ('latitude', models.FloatField(verbose_name='Enlem')),
                ('longitude', models.FloatField(verbose_name='Boylam')),
                ('interpretation', models.TextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('ascendant_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascendants', to='zodiac.zodiacsign', verbose_name='Yükselen Burç')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yükselen Burç',
                'verbose_name_plural': 'Yükselen Burçlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoonSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('birth_time', models.TimeField(verbose_name='Doğum Saati')),
                ('birth_place', models.CharField(max_length=200, verbose_name='Doğum Yeri')),
                ('latitude', models.FloatField(verbose_name='Enlem')),
                ('longitude', models.FloatField(verbose_name='Boylam')),
                ('interpretation', models.TextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('moon_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moon_signs', to='zodiac.zodiacsign', verbose_name='Ay Burcu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Ay Burcu',
                'verbose_name_plural': 'Ay Burçları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('birth_time', models.TimeField(blank=True, null=True, verbose_name='Doğum Saati')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='Doğum Yeri')),
                ('interpretation', models.TextField(blank=True, verbose_name='Genel Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('ascendant_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_ascendants', to='zodiac.zodiacsign', verbose_name='Yükselen Burç')),
                ('moon_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_moon_signs', to='zodiac.zodiacsign', verbose_name='Ay Burcu')),
                ('sun_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sun_signs', to='zodiac.zodiacsign', verbose_name='Güneş Burcu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kişisel Burç Profili',
                'verbose_name_plural': 'Kişisel Burç Profilleri',
            },
        ),
    ]
