# Generated by Django 5.0.2 on 2025-10-13 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0003_ascendant_moonsign_personalhoroscope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('general', models.TextField(verbose_name='Genel Yorum')),
                ('love', models.TextField(verbose_name='Aşk Hayatı')),
                ('career', models.TextField(verbose_name='Kariyer')),
                ('health', models.TextField(verbose_name='Sağlık')),
                ('money', models.TextField(verbose_name='Finans')),
                ('mood_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Ruh Hali Skoru')),
                ('lucky_number', models.IntegerField(verbose_name='Günün Şanslı Sayısı')),
                ('lucky_color', models.CharField(max_length=50, verbose_name='Günün Şanslı Rengi')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='openai', max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('zodiac_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zodiac.zodiacsign', verbose_name='Burç')),
            ],
            options={
                'verbose_name': 'Kullanıcı Günlük Burç Yorumu',
                'verbose_name_plural': 'Kullanıcı Günlük Burç Yorumları',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserMonthlyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Ay')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('general', models.TextField(verbose_name='Genel Yorum')),
                ('love', models.TextField(verbose_name='Aşk Hayatı')),
                ('career', models.TextField(verbose_name='Kariyer')),
                ('health', models.TextField(verbose_name='Sağlık')),
                ('money', models.TextField(verbose_name='Finans')),
                ('opportunities', models.TextField(verbose_name='Fırsatlar')),
                ('challenges', models.TextField(verbose_name='Zorluklar')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='openai', max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('zodiac_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zodiac.zodiacsign', verbose_name='Burç')),
            ],
            options={
                'verbose_name': 'Kullanıcı Aylık Burç Yorumu',
                'verbose_name_plural': 'Kullanıcı Aylık Burç Yorumları',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UserWeeklyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Hafta Başlangıcı')),
                ('week_end', models.DateField(verbose_name='Hafta Bitişi')),
                ('general', models.TextField(verbose_name='Genel Yorum')),
                ('love', models.TextField(verbose_name='Aşk Hayatı')),
                ('career', models.TextField(verbose_name='Kariyer')),
                ('health', models.TextField(verbose_name='Sağlık')),
                ('money', models.TextField(verbose_name='Finans')),
                ('advice', models.TextField(verbose_name='Haftalık Tavsiye')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='openai', max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('zodiac_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zodiac.zodiacsign', verbose_name='Burç')),
            ],
            options={
                'verbose_name': 'Kullanıcı Haftalık Burç Yorumu',
                'verbose_name_plural': 'Kullanıcı Haftalık Burç Yorumları',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
