# Generated by Django 5.0.2 on 2025-10-27 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0004_userdailyhoroscope_usermonthlyhoroscope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacsign',
            name='is_premium_only',
            field=models.BooleanField(default=False, help_text='Bu burç analizi sadece premium üyelere açık mı?', verbose_name='Sadece Premium Üyeler'),
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='token_cost',
            field=models.IntegerField(default=0, help_text='Bu burçtan detaylı analiz almak için gereken jeton sayısı. 0 = Ücretsiz', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jeton Maliyeti'),
        ),
    ]
