# Generated by Django 5.0.2 on 2025-10-02 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yayılım Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('card_count', models.IntegerField(verbose_name='Kart Sayısı')),
                ('positions', models.JSONField(help_text='Her pozisyonun anlamını içeren JSON', verbose_name='Pozisyon Anlamları')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri')], default='beginner', max_length=20, verbose_name='Zorluk Seviyesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarot Yayılımı',
                'verbose_name_plural': 'Tarot Yayılımları',
            },
        ),
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kart Adı')),
                ('name_en', models.CharField(max_length=100, verbose_name='İngilizce Adı')),
                ('suit', models.CharField(choices=[('major', 'Major Arcana'), ('cups', 'Cups (Kupa)'), ('pentacles', 'Pentacles (Tılsım)'), ('swords', 'Swords (Kılıç)'), ('wands', 'Wands (Değnek)')], max_length=20, verbose_name='Takım')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Numara')),
                ('upright_meaning', models.TextField(verbose_name='Düz Anlam')),
                ('reversed_meaning', models.TextField(verbose_name='Ters Anlam')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image_url', models.URLField(blank=True, verbose_name='Görsel URL')),
            ],
            options={
                'verbose_name': 'Tarot Kartı',
                'verbose_name_plural': 'Tarot Kartları',
                'unique_together': {('suit', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TarotReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Soru')),
                ('cards', models.JSONField(verbose_name='Çekilen Kartlar')),
                ('interpretation', models.TextField(verbose_name='Yorum')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], max_length=20, verbose_name='AI Sağlayıcı')),
                ('is_public', models.BooleanField(default=False, verbose_name='Herkese Açık')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.tarotspread', verbose_name='Yayılım')),
            ],
            options={
                'verbose_name': 'Tarot Okuma',
                'verbose_name_plural': 'Tarot Okumaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Ters Çekildi')),
                ('interpretation', models.TextField(verbose_name='Günlük Yorum')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], max_length=20, verbose_name='AI Sağlayıcı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.tarotcard', verbose_name='Kart')),
            ],
            options={
                'verbose_name': 'Günlük Kart',
                'verbose_name_plural': 'Günlük Kartlar',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
