# Generated by Django 5.0.2 on 2025-10-02 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sağlayıcı Adı')),
                ('display_name', models.CharField(max_length=100, verbose_name='Görünen Adı')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Anahtarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='Maksimum Token')),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Yaratıcılık Seviyesi')),
                ('system_prompt', models.TextField(default='Sen uzman bir tarot yorumcususun. Kartların anlamlarını detaylı ve anlayışlı bir şekilde açıkla.', verbose_name='Sistem Mesajı')),
            ],
            options={
                'verbose_name': 'AI Sağlayıcı',
                'verbose_name_plural': 'AI Sağlayıcıları',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Tarot Yorum', max_length=200, verbose_name='Site Başlığı')),
                ('site_description', models.TextField(default='AI destekli tarot falı platformu', verbose_name='Site Açıklaması')),
                ('site_keywords', models.CharField(default='tarot, fal, astroloji, ai', max_length=500, verbose_name='SEO Anahtar Kelimeleri')),
                ('default_ai_provider', models.CharField(choices=[('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini')], default='gemini', max_length=20, verbose_name='Varsayılan AI Sağlayıcı')),
                ('openai_api_key', models.CharField(blank=True, max_length=200, verbose_name='OpenAI API Anahtarı')),
                ('gemini_api_key', models.CharField(blank=True, max_length=200, verbose_name='Google Gemini API Anahtarı')),
                ('ai_response_max_length', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)], verbose_name='AI Yanıt Maksimum Uzunluk')),
                ('daily_reading_limit', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Günlük Okuma Limiti')),
                ('max_question_length', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)], verbose_name='Maksimum Soru Uzunluğu')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Bakım Modu')),
                ('maintenance_message', models.TextField(default='Site bakımda, lütfen daha sonra tekrar deneyin.', verbose_name='Bakım Mesajı')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='Kayıt Olma İzni')),
                ('allow_guest_reading', models.BooleanField(default=False, verbose_name='Misafir Okuma İzni')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='İletişim E-postası')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='Destek Telefonu')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('cache_timeout', models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)], verbose_name='Cache Süresi (saniye)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
