# Generated by Django 5.0.2 on 2025-10-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_aiprovider_sitesettings'),
    ]

    operations = [
    ]
