# Generated by Django 5.0.2 on 2025-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0003_auto_20251002_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.0-flash-exp', 'Gemini 2.0 Flash (Deneysel - En Hızlı)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (En Güçlü)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Hızlı ve Dengeli)'), ('gemini-pro', 'Gemini Pro (Standart)')], default='gemini-1.5-flash', max_length=50, verbose_name='Gemini Model'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='openai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (En Güçlü - Pahalı)'), ('gpt-4o-mini', 'GPT-4o Mini (Hızlı ve Uygun)'), ('gpt-4-turbo', 'GPT-4 Turbo (Güçlü)'), ('gpt-4', 'GPT-4 (Standart)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (Ekonomik)')], default='gpt-4o-mini', max_length=50, verbose_name='OpenAI Model'),
        ),
    ]
