# Generated by Django 5.0.2 on 2025-10-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0004_sitesettings_gemini_model_sitesettings_openai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.0-flash-exp', 'Gemini 2.0 Flash (Deneysel - En Hızlı)'), ('gemini-1.5-pro-latest', 'Gemini 1.5 Pro (En Güçlü)'), ('gemini-1.5-flash-latest', 'Gemini 1.5 Flash (Hızlı ve Dengeli)'), ('gemini-pro', 'Gemini Pro (Standart - Eski)')], default='gemini-1.5-flash-latest', max_length=50, verbose_name='Gemini Model'),
        ),
    ]
