# Generated by Django 5.0.2 on 2025-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0005_alter_sitesettings_gemini_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='openai_model',
            field=models.CharField(choices=[('o1', 'GPT-o1 (Reasoning Model - En Akıllı)'), ('o1-mini', 'GPT-o1 Mini (Hızlı Reasoning)'), ('gpt-4o', 'GPT-4o (En Güçlü - Multimodal)'), ('gpt-4o-mini', 'GPT-4o Mini (Hızlı ve Uygun)'), ('gpt-4-turbo', 'GPT-4 Turbo (Güçlü)'), ('gpt-4', 'GPT-4 (Standart)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (Ekonomik)')], default='gpt-4o', max_length=50, verbose_name='OpenAI Model'),
        ),
    ]
