# Generated by Django 5.0.2 on 2025-10-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0006_update_openai_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_ai_provider',
            field=models.CharField(choices=[('openai', 'AstroTarot AI (Primary)'), ('gemini', 'AstroTarot AI (Alternative)')], default='gemini', max_length=20, verbose_name='Varsayılan AI Motoru'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='AstroTarot AI API Anahtarı (Alternative)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.0-flash-exp', 'Alternative v2.0 Flash (Deneysel - En Hızlı)'), ('gemini-1.5-pro-latest', 'Alternative v1.5 Pro (En Güçlü)'), ('gemini-1.5-flash-latest', 'Alternative v1.5 Flash (Hızlı ve Dengeli)'), ('gemini-pro', 'Alternative Pro (Standart)')], default='gemini-1.5-flash-latest', max_length=50, verbose_name='AstroTarot AI Model (Alternative)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='AstroTarot AI API Anahtarı (Primary)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='openai_model',
            field=models.CharField(choices=[('o1', 'Expert Model (En Akıllı)'), ('o1-mini', 'Expert Mini (Hızlı Reasoning)'), ('gpt-4o', 'Advanced Model (Güçlü - Multimodal)'), ('gpt-4o-mini', 'Standard Model (Hızlı ve Uygun) ✅'), ('gpt-4-turbo', 'Advanced Turbo (Güçlü)'), ('gpt-4', 'Advanced (Standart)'), ('gpt-3.5-turbo', 'Basic (Ekonomik)')], default='gpt-4o-mini', max_length=50, verbose_name='AstroTarot AI Model (Primary)'),
        ),
    ]
