# Generated by Django 5.0.2 on 2025-10-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0009_switch_to_openrouter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line1', models.CharField(default='Geleceğinizin Sırları', max_length=100, verbose_name='Başlık Satır 1')),
                ('title_line2', models.CharField(default="Tarot'ta Saklı", max_length=100, verbose_name='Başlık Satır 2 (Vurgulu)')),
                ('subtitle', models.TextField(default='Yapay zeka destekli tarot falı ile kartların gizli mesajlarını keşfedin. 78 kart, sonsuz anlam, kişiselleştirilmiş yorumlar.', verbose_name='Alt Başlık')),
                ('show_announcement', models.BooleanField(default=False, verbose_name='Duyuru Göster')),
                ('announcement_text', models.CharField(default='Yeni Video Yayınlandı!', max_length=200, verbose_name='Duyuru Metni')),
                ('announcement_icon', models.CharField(default='fas fa-video', max_length=50, verbose_name='Duyuru İkonu (Font Awesome)')),
                ('announcement_link', models.URLField(blank=True, verbose_name='Duyuru Linki')),
                ('announcement_color', models.CharField(default='#FF0000', max_length=20, verbose_name='Duyuru Rengi')),
                ('primary_button_text', models.CharField(default='Hemen Fal Bak', max_length=50, verbose_name='Ana Buton Metni')),
                ('primary_button_url', models.CharField(default='/spreads/', max_length=200, verbose_name='Ana Buton URL')),
                ('secondary_button_text', models.CharField(default='Günlük Kart', max_length=50, verbose_name='İkinci Buton Metni')),
                ('secondary_button_url', models.CharField(default='/daily-card/', max_length=200, verbose_name='İkinci Buton URL')),
                ('background_gradient_start', models.CharField(default='#6B1B3D', max_length=20, verbose_name='Arka Plan Başlangıç Rengi')),
                ('background_gradient_end', models.CharField(default='#4A0E2A', max_length=20, verbose_name='Arka Plan Bitiş Rengi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Bölümü',
                'verbose_name_plural': 'Hero Bölümü',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
