# Generated by Django 5.0.2 on 2025-10-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0010_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='show_video',
            field=models.BooleanField(default=False, verbose_name='Video Göster'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='video_title',
            field=models.CharField(blank=True, help_text='Video için özel başlık (opsiyonel)', max_length=200, verbose_name='Video Başlığı'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='video_url',
            field=models.URLField(blank=True, help_text='Örnek: https://www.youtube.com/watch?v=VIDEO_ID veya https://youtu.be/VIDEO_ID', verbose_name='YouTube Video URL'),
        ),
    ]
