# Generated by Django 5.0.2 on 2025-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0011_herosection_show_video_herosection_video_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='primary_button_text',
            field=models.CharField(default='Rehberliğe Başla', max_length=50, verbose_name='Ana Buton Metni'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondary_button_text',
            field=models.CharField(default='Günlük İlham', max_length=50, verbose_name='İkinci Buton Metni'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(default='Yapay zeka destekli kişisel gelişim platformu. Duygusal denge, motivasyon ve içsel rehberlik için algoritmalarla desteklenen özel yöntemler.', verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_line1',
            field=models.CharField(default='İçsel Farkındalığınızı', max_length=100, verbose_name='Başlık Satır 1'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_line2',
            field=models.CharField(default='Keşfedin', max_length=100, verbose_name='Başlık Satır 2 (Vurgulu)'),
        ),
    ]
