# Generated by Django 5.0.2 on 2025-10-27 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0012_alter_herosection_primary_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotspread',
            name='is_premium_only',
            field=models.BooleanField(default=False, help_text='Bu yayılım sadece premium üyelere açık mı?', verbose_name='Sadece Premium Üyeler'),
        ),
        migrations.AddField(
            model_name='tarotspread',
            name='token_cost',
            field=models.IntegerField(default=0, help_text='Bu yayılımı kullanmak için gereken jeton sayısı. 0 = Ücretsiz', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jeton Maliyeti'),
        ),
    ]
